language: d

d:
  - dmd
  - ldc
script: dub test --compiler=${DC}
before_script:
  - sudo apt-get update
  - sudo apt-get install -y -q libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

